"""
AgentVision project installer.

When AgentVision bridges to a program for the first time, it doesn't just
*read* the project — it INSTALLS the full diagnostic infrastructure into
that project. This module is the single source of truth for what gets
created and where.

Contract: given a project_root, produce a project that is fully diagnosable
by AgentVision. Anything missing gets created with sane defaults; anything
already present is left alone.

What gets installed
───────────────────
  <project>/.agentvision/                  ← AgentVision-owned dir, never
                                              touched by the bridged program
    attached.json                          ← marker + metadata (when, name, av_root)
    state.json                             ← live program state (HP/MP/run_id…)
    schema.json                            ← schema for the project's events
    README.md                              ← what these files are
  <project>/log/                           ← project's own log dir (if missing)
    log.txt                                ← text log
    actions.jsonl                          ← structured event stream
    stats/                                 ← stats sub-dir
    crashes/                               ← crash dumps
  <project>/config/                        ← config dir (if missing)
  <project>/test/                          ← test dir (if missing)
  <project>/sitecustomize.py               ← Python auto-instrumentation
                                              (only if .py files exist + no
                                               existing sitecustomize.py)

Idempotent: safe to call multiple times. Returns a report of what was
created vs already-existed so the GUI can show the user.
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


AV_ROOT = Path(__file__).resolve().parent.parent

# Default JSON content templates ─────────────────────────────────────────────

_STATE_JSON_TEMPLATE = {
    "_comment": (
        "Live program state, written by the bridged program at runtime. "
        "AgentVision reads this to populate the 'wide event' state at any "
        "moment in time. Update freely; AgentVision watches mtime."
    ),
    "version": 1,
    "run_id": None,
    "started_at": None,
    "updated_at": None,
    "fields": {},
}

_SCHEMA_JSON_TEMPLATE = {
    "_comment": (
        "Event schema for this project. List the (category, name) pairs "
        "the program emits so the bridge can pre-populate /events/schema. "
        "AgentVision will also auto-discover events not listed here."
    ),
    "version": 1,
    "categories": {
        "key":     "Keyboard input events",
        "mouse":   "Mouse events",
        "log":     "Free-form log lines",
        "event":   "Domain-specific structured events",
        "metric":  "Numeric measurements (gauges, counters)",
        "error":   "Errors and exceptions",
        "process": "Process lifecycle (start/stop/exit)",
    },
    "events": [],
}

_README_TEXT = """\
# .agentvision/

This directory was created by AgentVision when it bridged to this project.
It contains the diagnostic infrastructure AgentVision uses to observe and
debug the program.

## Files

- **attached.json** — Marker file. When this exists, AgentVision recognizes
  the project. Contains the profile name and when bridging happened.
- **state.json** — Live program state. The bridged program may write to this
  at runtime; AgentVision reads it on every snapshot to capture HP/MP/run_id/
  any other gauge or signal you want correlated with screenshots.
- **schema.json** — Optional schema declaration for the events your program
  emits. AgentVision auto-discovers events at runtime, but pre-declaring
  them here makes the events vocabulary visible immediately.

## Safe to commit?

Yes — this is configuration, not runtime data. You may add `.agentvision/`
to `.gitignore` if you prefer; both choices are fine.

## How to remove

Just delete this directory. AgentVision will treat the project as
"not attached" the next time it scans.
"""

_SITECUSTOMIZE_TEMPLATE = """\
# AgentVision auto-instrumentation hook.
# Generated by AgentVision installer. Zero impact if AgentVision isn't installed.
# Idempotent via AGENTVISION_HOOKED env-var guard.

import os, sys

if not os.environ.get("AGENTVISION_HOOKED"):
    try:
        _av_proj = os.path.dirname(os.path.abspath(__file__))
        os.environ.setdefault("AGENTVISION_PROJECT", _av_proj)
        # Canonical sink folder for the universal bridge: <project>/agentvision/.
        # Resolved relative to this file so the project stays portable.
        os.environ.setdefault("AGENTVISION_LOG_DIR",
                              os.path.join(_av_proj, "agentvision"))

        # ── stdout/stderr tee → agentvision/raw_output.txt ────────────────
        if not os.environ.get("AGENTVISION_RAW_HOOKED"):
            try:
                _raw_path = os.path.join(_av_proj, "agentvision", "raw_output.txt")
                os.makedirs(os.path.dirname(_raw_path), exist_ok=True)

                class _TeeStream:
                    def __init__(self, original, filepath):
                        self._orig = original
                        try:
                            self._file = open(filepath, "a", encoding="utf-8",
                                              errors="replace", buffering=1)
                        except Exception:
                            self._file = None
                    def write(self, data):
                        try: self._orig.write(data); self._orig.flush()
                        except Exception: pass
                        try:
                            if self._file: self._file.write(data); self._file.flush()
                        except Exception: pass
                    def flush(self):
                        try: self._orig.flush()
                        except Exception: pass
                        try:
                            if self._file: self._file.flush()
                        except Exception: pass
                    def fileno(self): return self._orig.fileno()
                    def __getattr__(self, name): return getattr(self._orig, name)

                sys.stdout = _TeeStream(sys.stdout, _raw_path)
                sys.stderr = _TeeStream(sys.stderr, _raw_path)
                os.environ["AGENTVISION_RAW_HOOKED"] = "1"
            except Exception:
                pass

        # ── AgentVision in-process runtime hooks ──────────────────────────
        # Only the hooks the agent selected in its bridge plan. Empty/absent means
        # every hook, which is what a pre-selection install and a bare
        # `agentvision run` both want.
        if {hooks!r}:
            os.environ.setdefault("AGENTVISION_HOOKS", {hooks!r})
        try:
            sys.path.insert(0, {av_root!r})
            from agent_bootstrap.av_runtime import install_all_hooks
            install_all_hooks()
        except Exception:
            pass

        os.environ["AGENTVISION_HOOKED"] = "1"
    except Exception:
        pass
"""


# ── Report structure ────────────────────────────────────────────────────────

@dataclass
class InstallReport:
    """What the installer did. The GUI shows this back to the user."""
    project_root: Path
    created:    list[str] = field(default_factory=list)   # new paths
    existed:    list[str] = field(default_factory=list)   # pre-existing
    skipped:    list[str] = field(default_factory=list)   # not applicable
    errors:     list[tuple[str, str]] = field(default_factory=list)
    profile_overrides: dict = field(default_factory=dict)
    # ── Universal auto-bridge metadata ──────────────────────────────────────
    language:   str  = ""                              # detected/declared language
    emitter:    dict = field(default_factory=dict)     # kind, files, run_env, howto
    #: What the agent's plan asked for, and whether that selection actually gates
    #: what arms at runtime. Reported separately so a commit can never imply a
    #: per-emitter build on a language where only one artifact exists.
    emitters_requested: list = field(default_factory=list)
    selection_enforced: bool = False
    #: Per-id answer to the selection: [{id, enforced, how}]. A single blanket
    #: `selection_enforced: false` could not distinguish "this id is a facet of the
    #: one artifact this language builds" from "this id does nothing at all here",
    #: and only the second is a mistake the agent should fix.
    emitter_selection: list = field(default_factory=list)
    #: Hooks that arm even though the plan did NOT select them, or {} when the
    #: plan's exclusions really are honoured. emitter_selection cannot carry this:
    #: it answers per NAMED id, and this is entirely about the ids left out.
    emitter_selection_fail_open: dict = field(default_factory=dict)
    #: Free-text consequences of THIS install that the agent must read — a
    #: selection that changed a profile flag, a capability that needs a separate
    #: process running. Distinct from `errors`: nothing failed, but acting as if
    #: the install were complete would produce a wrong reading.
    notes: list = field(default_factory=list)

    def to_dict(self) -> dict:
        """Machine-readable form of what the install actually did.

        bridge_server's commit path calls this and falls back to `{"summary": ...}`
        on AttributeError. Because this method did not exist, the fallback ALWAYS
        ran, so `built.install` was a multi-line human string with no fields — an
        agent asking "which emitter got installed?" got prose it could not parse,
        and could not distinguish a real install from a no-op.
        """
        return {
            "project_root": str(self.project_root),
            "language": self.language,
            "emitter": dict(self.emitter or {}),
            "emitters_requested": list(self.emitters_requested),
            "selection_enforced": bool(self.selection_enforced),
            "emitter_selection": list(self.emitter_selection),
            "emitter_selection_fail_open": dict(
                self.emitter_selection_fail_open or {}),
            "notes": list(self.notes),
            "created": list(self.created),
            "existed": list(self.existed),
            "skipped": list(self.skipped),
            "errors": [{"path": p, "error": e} for p, e in (self.errors or [])],
            "profile_overrides": dict(self.profile_overrides or {}),
            "counts": {"created": len(self.created), "existed": len(self.existed),
                       "skipped": len(self.skipped), "errors": len(self.errors)},
            "summary": self.summary(),
        }

    def summary(self) -> str:
        lines = [f"AgentVision install → {self.project_root}"]
        if self.language:
            k = (self.emitter or {}).get("kind", "?")
            lines.append(f"  language: {self.language}   emitter: {k}")
        if self.created:
            lines.append(f"  ✓ Created {len(self.created)}:")
            for p in self.created:
                lines.append(f"      + {p}")
        if self.existed:
            lines.append(f"  · Already present {len(self.existed)}:")
            for p in self.existed:
                lines.append(f"      = {p}")
        if self.skipped:
            lines.append(f"  ⊘ Skipped {len(self.skipped)}:")
            for p in self.skipped:
                lines.append(f"      - {p}")
        if self.errors:
            lines.append(f"  ⚠ Errors {len(self.errors)}:")
            for p, e in self.errors:
                lines.append(f"      ! {p}: {e}")
        return "\n".join(lines)


# ── Atomic helpers ──────────────────────────────────────────────────────────

def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")


def _ensure_dir(p: Path, report: InstallReport) -> None:
    rel = _relpath(p, report.project_root)
    if p.exists() and p.is_dir():
        report.existed.append(f"dir  {rel}/")
        return
    try:
        p.mkdir(parents=True, exist_ok=True)
        report.created.append(f"dir  {rel}/")
    except Exception as e:
        report.errors.append((str(p), f"mkdir failed: {e}"))


def _ensure_file(p: Path, content: str, report: InstallReport,
                 *, overwrite: bool = False) -> None:
    rel = _relpath(p, report.project_root)
    if p.exists() and not overwrite:
        report.existed.append(f"file {rel}")
        return
    try:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
        report.created.append(f"file {rel}")
    except Exception as e:
        report.errors.append((str(p), f"write failed: {e}"))


def _ensure_empty_file(p: Path, report: InstallReport) -> None:
    rel = _relpath(p, report.project_root)
    if p.exists():
        report.existed.append(f"file {rel}")
        return
    try:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.touch()
        report.created.append(f"file {rel}")
    except Exception as e:
        report.errors.append((str(p), f"touch failed: {e}"))


def _ensure_json(p: Path, payload: dict, report: InstallReport) -> None:
    """Write JSON only if file doesn't exist; preserve any user edits."""
    rel = _relpath(p, report.project_root)
    if p.exists():
        report.existed.append(f"json {rel}")
        return
    try:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        report.created.append(f"json {rel}")
    except Exception as e:
        report.errors.append((str(p), f"json write failed: {e}"))


def _relpath(p: Path, root: Path) -> str:
    try:
        return str(p.relative_to(root))
    except ValueError:
        return str(p)


# ── The install function ────────────────────────────────────────────────────

def _detect_language(root: Path) -> str:
    """Thin delegate to the ONE shared detector — connectors.log_sources.
    detect_language (marker files + extension census). Kept as a wrapper only so
    both import styles resolve; it never reimplements detection, so cli.py,
    installer.py and the profile wiring can never drift."""
    try:
        from connectors import log_sources as _ls
    except Exception:
        try:
            from python_backend.connectors import log_sources as _ls  # type: ignore
        except Exception:
            return ""
    try:
        return _ls.detect_language(str(root))
    except Exception:
        return ""


def install_into_project(project_root: str | Path, *,
                         profile_name: str = "",
                         install_python_hook: bool = True,
                         language: str = "",
                         emitters: Optional[list] = None,
                         ) -> InstallReport:
    """UNIVERSAL auto-bridge install — scaffold the OUTPUT side of the bridge
    into project_root for ANY language, with zero code changes to the target.

    On first attach AgentVision:
      1. detects the project's language (or uses the `language` arg),
      2. scaffolds a self-contained `agentvision/` folder inside the project
         holding the sink files (actions.jsonl / log.txt), live state, a
         manifest, and a per-language OUTPUT EMITTER, and
      3. wires zero-effort logging: Python gets a project-root sitecustomize.py
         (true autoload); Node/Ruby get an env-autoloaded preload shim; Java/
         .NET get a logger config drop-in; compiled languages use the
         `agentvision run` stdout/stderr tee. See python_backend/emitters.py.

    Idempotent. Returns an InstallReport (created/existed/skipped/errors +
    profile_overrides + detected language + emitter metadata).
    """
    from emitters import (build_emitter, SINK_DIRNAME, ACTIONS_SINK, TEXT_SINK)

    root = Path(project_root).expanduser().resolve()
    report = InstallReport(project_root=root)

    if not root.exists():
        report.errors.append((str(root), "project_root does not exist"))
        return report

    # ── Detect language ──────────────────────────────────────────────────
    lang = (language or "").strip().lower() or _detect_language(root)
    report.language = lang or "unknown"

    # ── The canonical AgentVision folder: <project>/agentvision/ ──────────
    # ONE self-contained folder holding everything "the other side" needs:
    # the sinks, live state, the manifest/marker, and the emitter.
    av_dir = root / SINK_DIRNAME
    _ensure_dir(av_dir, report)

    _ensure_empty_file(av_dir / ACTIONS_SINK, report)     # structured JSONL sink
    _ensure_empty_file(av_dir / TEXT_SINK,    report)     # plain-text sink
    _ensure_json(av_dir / "state.json", _STATE_JSON_TEMPLATE, report)
    _ensure_dir(av_dir / "stats",   report)
    _ensure_dir(av_dir / "crashes", report)
    _ensure_dir(av_dir / "emitters", report)

    actions_path = av_dir / ACTIONS_SINK
    text_path    = av_dir / TEXT_SINK

    # ── Build + write the per-language emitter ────────────────────────────
    # `emitters` is the agent's selection from its bridge plan. For in-process
    # hook languages it becomes AGENTVISION_HOOKS so only the chosen hooks arm;
    # elsewhere there is a single artifact and the selection is recorded, not
    # enforced (spec.selection_enforced says which).
    spec = build_emitter(lang, AV_ROOT, root, selected=emitters)
    report.emitters_requested = list(emitters or [])
    report.selection_enforced = bool(getattr(spec, "selection_enforced", False))
    try:
        from emitters import selection_report as _sel_report
    except Exception:
        from python_backend.emitters import selection_report as _sel_report
    report.emitter_selection = _sel_report(lang, emitters)
    # Hooks that arm despite NOT being selected. selection_report only answers for
    # ids the plan named, so without this an over-install is invisible: the agent
    # reads five hooks' output believing it chose one.
    try:
        from emitters import hooks_fail_open as _fail_open
    except Exception:
        from python_backend.emitters import hooks_fail_open as _fail_open
    _leak = _fail_open(lang, emitters)
    if _leak:
        report.emitter_selection_fail_open = _leak
    # The literal AGENTVISION_HOOKS value baked into the generated sitecustomize.
    # "" means every hook, so an unselected install behaves exactly as before.
    _hooks_str = (spec.run_env or {}).get("AGENTVISION_HOOKS", "")
    emitter_abs = ""     # absolute path of the primary emitter file (for run_env)
    for rel, content in spec.files.items():
        p = av_dir / rel
        _ensure_file(p, content, report, overwrite=True)
        # The primary emitter file is the one referenced by run_env's {emitter}.
        if rel.endswith((".js", ".rb")) and not emitter_abs:
            emitter_abs = str(p)

    # run_env with the {emitter} placeholder resolved to the absolute path.
    run_env = {k: v.replace("{emitter}", emitter_abs) if emitter_abs else v
               for k, v in (spec.run_env or {}).items()}
    report.emitter = {
        "language":     spec.language,
        "kind":         spec.kind,
        "autoload":     spec.autoload,
        "verify":       spec.verify,
        "run_env":      run_env,
        "files":        [f"{SINK_DIRNAME}/{r}" for r in spec.files.keys()],
        "how_to_load":  spec.load_instructions,
        "notes":        spec.notes,
    }

    # ── Python: true-autoload sitecustomize.py at the project root ────────
    # (Points AGENTVISION_LOG_DIR at the canonical agentvision/ folder.)
    if install_python_hook and lang == "python":
        site = root / "sitecustomize.py"
        if site.exists():
            report.existed.append(f"file {_relpath(site, root)} (left untouched)")
            # Leaving the file alone is right — it is the project's, not ours. But
            # the CONSEQUENCE is severe and was reported only as a line in
            # `existed`: without our bootstrap, install_all_hooks never runs, so
            # EVERY in-process emitter the plan selected is silently inert. The
            # agent would then read an empty actions.jsonl as "the program logged
            # nothing", which is the exact false read this project exists to stop.
            try:
                _txt = site.read_text(encoding="utf-8", errors="replace")
            except Exception:
                _txt = ""
            if "av_runtime" not in _txt and "install_all_hooks" not in _txt:
                report.notes.append(
                    f"IN-PROCESS EMITTERS DID NOT INSTALL. {_relpath(site, root)} "
                    "already exists and was left untouched, so the AgentVision "
                    "bootstrap is not in it and install_all_hooks() never runs. "
                    "Every hook-based emitter in your plan (stdout_tee, "
                    "logging_bridge, uncaught_exceptions, swallowed_exceptions, "
                    "lifecycle) is INERT. Do not read an empty "
                    "agentvision/actions.jsonl as 'the program produced no "
                    "output'. Fix by adding these two lines to that file: "
                    "`import sys; sys.path.insert(0, r\"" + str(AV_ROOT) + "\")` "
                    "then `from agent_bootstrap.av_runtime import "
                    "install_all_hooks; install_all_hooks()` — or launch via "
                    "`agentvision run -- <cmd>`, which does not depend on this "
                    "file. Confirm either way by looking for an av.bootstrap.start "
                    "record in the sink.")
        else:
            try:
                site.write_text(
                    _SITECUSTOMIZE_TEMPLATE.format(av_root=str(AV_ROOT),
                                                   hooks=_hooks_str),
                    encoding="utf-8")
                report.created.append(f"file {_relpath(site, root)}")
            except Exception as e:
                report.errors.append((str(site), f"write failed: {e}"))
    elif install_python_hook and any(root.glob("*.py")):
        # Mixed project that has .py at root but wasn't detected as Python —
        # still drop the hook so Python parts are covered.
        site = root / "sitecustomize.py"
        if not site.exists():
            try:
                site.write_text(
                    _SITECUSTOMIZE_TEMPLATE.format(av_root=str(AV_ROOT),
                                                   hooks=_hooks_str),
                    encoding="utf-8")
                report.created.append(f"file {_relpath(site, root)} (mixed project)")
            except Exception as e:
                report.errors.append((str(site), f"write failed: {e}"))

    # ── Manifest / marker (the attach record + full wiring, in JSON) ──────
    manifest = {
        "version":     2,
        "name":        profile_name or root.name,
        "attached_at": _now_iso(),
        "av_root":     str(AV_ROOT),
        "language":    lang or "unknown",
        "sinks": {
            "actions": str(actions_path),
            "text":    str(text_path),
            "state":   str(av_dir / "state.json"),
        },
        "emitter":     report.emitter,
        # The agent's decision, recorded next to what was built so the two can be
        # compared later without re-reading the plan file.
        "emitters_requested": list(report.emitters_requested),
        "emitter_selection_enforced": bool(report.selection_enforced),
        "emitter_selection": list(report.emitter_selection),
        "schema":      _SCHEMA_JSON_TEMPLATE,
        "how_it_works": (
            "AgentVision READS the sinks in this folder (input side, built in) "
            "and the emitter here makes THIS program WRITE them (output side). "
            "Launch via `agentvision run -- <cmd>` for zero-effort bridging in "
            "any language."),
    }
    try:
        (av_dir / "manifest.json").write_text(
            json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        report.created.append(f"file {SINK_DIRNAME}/manifest.json")
    except Exception as e:
        report.errors.append((str(av_dir / "manifest.json"), f"write failed: {e}"))
    _ensure_file(av_dir / "README.md", _README_TEXT, report, overwrite=True)

    # ── Profile-tab field overrides (canonical agentvision/ sinks) ────────
    report.profile_overrides["state_file"]      = str(av_dir / "state.json")
    report.profile_overrides["log_file"]        = str(text_path)
    report.profile_overrides["action_log_file"] = str(actions_path)
    report.profile_overrides["stats_folder"]    = str(av_dir / "stats")
    report.profile_overrides["language"]        = lang
    # Multi-source wiring: both sinks with the right adapters, ready for the
    # bridge's normalized reader.
    report.profile_overrides["log_sources"] = [
        {"path": str(actions_path), "adapter": "jsonl", "label": "events"},
        {"path": str(text_path),    "adapter": "auto",  "label": "textlog"},
    ]

    # `user_input` builds no file: the capability is a profile flag plus a daemon,
    # so honouring the selection means flipping the flag here. Without this the id
    # was selectable in the catalog and did nothing — the worst of both, since the
    # agent would then read an empty input log as "the human pressed nothing".
    # Only ever turned ON by an explicit selection; never turned off, because the
    # human may have enabled it themselves in the GUI and a bridge rebuild must not
    # silently revoke that.
    if "user_input" in (emitters or []):
        report.profile_overrides["capture_user_input"] = True
        report.notes.append(
            "user_input selected -> capture_user_input=true on the profile. This "
            "records the human's real keyboard/mouse SYSTEM-WIDE, so confirm they "
            "agreed. It also needs the daemon running (`agentvision daemon start`); "
            "if it is not, you get silence rather than an error, so check "
            "av_daemon_status() before reading an empty input log as 'no input'.")

    # ── .gitignore hint (optional, non-fatal) ─────────────────────────────
    gi = root / ".gitignore"
    if gi.exists():
        try:
            text = gi.read_text(encoding="utf-8", errors="replace")
            need = [e for e in ("agentvision/actions.jsonl", "agentvision/log.txt",
                                "agentvision/crashes/", "agentvision/state.json")
                    if e not in text]
            if need:
                with gi.open("a", encoding="utf-8") as f:
                    f.write("\n# AgentVision diagnostic data (runtime, not config)\n")
                    for line in need:
                        f.write(line + "\n")
                report.created.append(f"appended {len(need)} lines to .gitignore")
            else:
                report.existed.append("file .gitignore (already covers AV)")
        except Exception as e:
            report.errors.append((str(gi), f"gitignore append failed: {e}"))
    else:
        report.skipped.append(".gitignore (project has none — not creating)")

    return report
